<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>StringMaster | Learn Guitar Online</title>
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Space+Grotesk:wght@300;400;500;600;700&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="templatemo-606-string-master.css">
<!--

TemplateMo 606 String Master

https://templatemo.com/tm-606-string-master

-->
</head>
<body>

  <!-- Navigation -->
  <nav>
    <div class="nav-container">
      <a href="#" class="logo">
        <div class="logo-icon">♪</div>
        StringMaster
      </a>
      <ul class="nav-links">
        <li><a href="#features">Features</a></li>
        <li><a href="#pricing">Pricing</a></li>
        <li><a href="#instructors">Instructors</a></li>
        <li><a href="#testimonials">Reviews</a></li>
      </ul>
      <a href="#pricing" class="nav-cta"><span>Start Free Trial</span></a>
      <button class="mobile-menu-btn">☰</button>
    </div>
  </nav>

  <!-- Hero Section -->
  <!-- TIP: To enable full-screen hero, uncomment "min-height: 100vh" in the .hero CSS -->
  <section class="hero">
    <div class="hero-container">
      <div class="hero-content">
        <div class="hero-badge">
          <span>●</span> New: AI-powered chord recognition
        </div>
        <h1>Master guitar with <span class="highlight">interactive</span> lessons</h1>
        <p class="hero-description">
          Learn at your own pace with our visual fretboard trainer. 
          From beginner chords to advanced techniques — all in one platform.
        </p>
        <div class="hero-buttons">
          <a href="#pricing" class="btn-primary">
            Start Learning →
          </a>
          <a href="#features" class="btn-secondary">
            See How It Works
          </a>
        </div>
        <div class="hero-stats">
          <div class="stat">
            <div class="stat-value">50K+</div>
            <div class="stat-label">Active Students</div>
          </div>
          <div class="stat">
            <div class="stat-value">200+</div>
            <div class="stat-label">Video Lessons</div>
          </div>
          <div class="stat">
            <div class="stat-value">4.9</div>
            <div class="stat-label">App Rating</div>
          </div>
        </div>
      </div>

      <!-- Interactive Guitar -->
      <div class="guitar-wrapper">
        <div class="guitar-card">
          <div class="guitar-header">
            <span class="guitar-title">Try it — Click a chord</span>
            <div class="guitar-controls">
              <button class="chord-btn" data-chord="C">C</button>
              <button class="chord-btn" data-chord="G">G</button>
              <button class="chord-btn" data-chord="Am">Am</button>
              <button class="chord-btn" data-chord="F">F</button>
              <button class="chord-btn" data-chord="D">D</button>
              <button class="chord-btn" data-chord="Em">Em</button>
            </div>
          </div>
          <div class="guitar-neck">
            <div class="fretboard">
              <div class="nut"></div>
              <div class="fretboard-grid" id="fretboard">
                <div class="string-labels">
                  <div class="string-label">E</div>
                  <div class="string-label">B</div>
                  <div class="string-label">G</div>
                  <div class="string-label">D</div>
                  <div class="string-label">A</div>
                  <div class="string-label">E</div>
                </div>
                <!-- Frets generated by JS -->
              </div>
            </div>
          </div>
          <div class="guitar-footer">
            <div class="guitar-footer-row">
              <span class="guitar-hint">Click frets to play notes</span>
              <div class="footer-controls">
                <button class="clear-btn" id="clearBtn">Clear</button>
                <div class="sound-toggle">
                  <span>Sound</span>
                  <div class="toggle-switch active" id="soundToggle"></div>
                </div>
              </div>
            </div>
            <div class="song-player">
              <button class="play-btn" id="playBtn">▶</button>
              <div class="song-info">
                <div class="song-title" id="songTitle">Greensleeves</div>
                <div class="song-progress">
                  <div class="song-progress-bar" id="progressBar"></div>
                </div>
              </div>
              <select class="song-select" id="songSelect">
                <option value="greensleeves">Greensleeves</option>
                <option value="houseoftherisingsun">House of the Rising Sun</option>
                <option value="amazinggrace">Amazing Grace</option>
              </select>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

  <!-- Features Section -->
  <section class="features" id="features">
    <div class="section-container">
      <div class="section-header">
        <div class="section-label">Features</div>
        <h2 class="section-title">Everything you need to learn guitar</h2>
        <p class="section-description">
          Our platform combines visual learning with hands-on practice 
          to accelerate your guitar journey.
        </p>
      </div>
      <div class="features-grid">
        <div class="feature-card">
          <div class="feature-icon">
            <svg width="28" height="28" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round">
              <path d="M11.5 2a8.5 8.5 0 0 1 0 17v3l-3-3-3 3v-3a8.5 8.5 0 0 1 6-16z"/>
              <circle cx="11.5" cy="10.5" r="3"/>
              <path d="M11.5 7.5v-2M14.5 10.5h2M11.5 13.5v2M8.5 10.5h-2"/>
            </svg>
          </div>
          <h3>Interactive Fretboard</h3>
          <p>Visual chord diagrams that show exactly where to place your fingers. Practice anywhere, anytime.</p>
        </div>
        <div class="feature-card">
          <div class="feature-icon">
            <svg width="28" height="28" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round">
              <rect x="2" y="4" width="20" height="14" rx="2"/>
              <circle cx="12" cy="11" r="3"/>
              <path d="M10.5 9.5l4 3-4 3z" fill="currentColor"/>
            </svg>
          </div>
          <h3>HD Video Lessons</h3>
          <p>200+ professionally filmed lessons from beginner basics to advanced techniques.</p>
        </div>
        <div class="feature-card">
          <div class="feature-icon">
            <svg width="28" height="28" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round">
              <path d="M12 2v4M12 18v4M4.93 4.93l2.83 2.83M16.24 16.24l2.83 2.83M2 12h4M18 12h4M4.93 19.07l2.83-2.83M16.24 7.76l2.83-2.83"/>
              <circle cx="12" cy="12" r="4"/>
              <path d="M12 8v4l2 2"/>
            </svg>
          </div>
          <h3>Progress Tracking</h3>
          <p>Set goals, track your practice time, and watch your skills improve over time.</p>
        </div>
        <div class="feature-card">
          <div class="feature-icon">
            <svg width="28" height="28" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round">
              <path d="M9 18V5l12-2v13"/>
              <circle cx="6" cy="18" r="3"/>
              <circle cx="18" cy="16" r="3"/>
              <path d="M9 9l12-2"/>
            </svg>
          </div>
          <h3>Song Library</h3>
          <p>Learn your favorite songs with tabs, chords, and play-along backing tracks.</p>
        </div>
        <div class="feature-card">
          <div class="feature-icon">
            <svg width="28" height="28" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round">
              <path d="M12 2a3 3 0 0 0-3 3v7a3 3 0 0 0 6 0V5a3 3 0 0 0-3-3z"/>
              <path d="M19 10v2a7 7 0 0 1-14 0v-2"/>
              <line x1="12" y1="19" x2="12" y2="22"/>
              <path d="M8 22h8"/>
              <path d="M3 10l1.5 1.5M21 10l-1.5 1.5M3 14l1.5-1.5M21 14l-1.5-1.5"/>
            </svg>
          </div>
          <h3>AI Feedback</h3>
          <p>Get real-time feedback on your playing through our audio recognition technology.</p>
        </div>
        <div class="feature-card">
          <div class="feature-icon">
            <svg width="28" height="28" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round">
              <path d="M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2"/>
              <circle cx="9" cy="7" r="4"/>
              <path d="M23 21v-2a4 4 0 0 0-3-3.87"/>
              <path d="M16 3.13a4 4 0 0 1 0 7.75"/>
            </svg>
          </div>
          <h3>Community</h3>
          <p>Connect with fellow learners, share progress, and get tips from experienced players.</p>
        </div>
      </div>
    </div>
  </section>

  <!-- Pricing Section -->
  <section class="pricing" id="pricing">
    <div class="section-container">
      <div class="section-header">
        <div class="section-label">Pricing</div>
        <h2 class="section-title">Simple, transparent pricing</h2>
        <p class="section-description">
          Start with a free trial. No credit card required.
        </p>
      </div>
      <div class="billing-toggle">
        <button class="billing-option active" data-billing="monthly">Monthly</button>
        <button class="billing-option" data-billing="quarterly">
          Quarterly
          <span class="discount-badge">-15%</span>
        </button>
        <button class="billing-option" data-billing="yearly">
          Yearly
          <span class="discount-badge">-30%</span>
        </button>
      </div>
      <div class="pricing-grid">
        <div class="pricing-card">
          <div class="pricing-name">Starter</div>
          <div class="pricing-price">
            <span class="currency"></span>Free
          </div>
          <div class="pricing-billed"></div>
          <div class="pricing-savings"></div>
          <p class="pricing-description">Perfect for trying out the basics</p>
          <ul class="pricing-features">
            <li>10 beginner lessons</li>
            <li>Interactive fretboard</li>
            <li>5 songs with tabs</li>
            <li>Community access</li>
          </ul>
          <a href="#" class="pricing-btn">Get Started</a>
        </div>
        <div class="pricing-card featured" id="proCard">
          <div class="pricing-name">Pro</div>
          <div class="pricing-price">
            <span class="currency">$</span><span id="proPrice">30</span><span class="period">/mo</span>
          </div>
          <div class="pricing-billed" id="proBilled"></div>
          <div class="pricing-savings" id="proSavings"></div>
          <p class="pricing-description">For serious learners</p>
          <ul class="pricing-features">
            <li>All 200+ video lessons</li>
            <li>Full song library (500+)</li>
            <li>AI feedback on playing</li>
            <li>Progress tracking</li>
            <li>Download lessons offline</li>
          </ul>
          <a href="#" class="pricing-btn">Start Free Trial</a>
        </div>
        <div class="pricing-card">
          <div class="pricing-name">Lifetime</div>
          <div class="pricing-price">
            <span class="currency">$</span>440
          </div>
          <div class="pricing-billed">One-time payment</div>
          <div class="pricing-savings">Best value</div>
          <p class="pricing-description">Forever access, no recurring fees</p>
          <ul class="pricing-features">
            <li>Everything in Pro</li>
            <li>1-on-1 coaching session</li>
            <li>Exclusive masterclasses</li>
            <li>Priority support</li>
            <li>All future updates</li>
          </ul>
          <a href="#" class="pricing-btn">Get Lifetime Access</a>
        </div>
      </div>
    </div>
  </section>

  <!-- Instructors Section -->
  <section class="instructors" id="instructors">
    <div class="section-container">
      <div class="section-header">
        <div class="section-label">Instructors</div>
        <h2 class="section-title">Learn from the best</h2>
        <p class="section-description">
          Our instructors have decades of combined experience and a passion for teaching.
        </p>
      </div>
      <div class="instructors-grid">
        <div class="instructor-card">
          <div class="instructor-image">
            <img src="images/acoustic-specialist.jpg" alt="Marcus Chen">
          </div>
          <div class="instructor-name">Marcus Chen</div>
          <div class="instructor-role">Acoustic Specialist</div>
          <p class="instructor-bio">15 years teaching, Berklee graduate</p>
        </div>
        <div class="instructor-card">
          <div class="instructor-image">
            <img src="images/fingerstyle-expert.jpg" alt="Sarah Williams">
          </div>
          <div class="instructor-name">Sarah Williams</div>
          <div class="instructor-role">Fingerstyle Expert</div>
          <p class="instructor-bio">YouTube educator, 2M subscribers</p>
        </div>
        <div class="instructor-card">
          <div class="instructor-image">
            <img src="images/blues-rock-guitar.jpg" alt="James Rodriguez">
          </div>
          <div class="instructor-name">James Rodriguez</div>
          <div class="instructor-role">Blues & Rock</div>
          <p class="instructor-bio">Session guitarist, 20+ albums</p>
        </div>
        <div class="instructor-card">
          <div class="instructor-image">
            <img src="images/music-theory-instructor.jpg" alt="Emily Park">
          </div>
          <div class="instructor-name">Emily Park</div>
          <div class="instructor-role">Music Theory</div>
          <p class="instructor-bio">PhD in Music, award-winning educator</p>
        </div>
      </div>
    </div>
  </section>

  <!-- Testimonials Section -->
  <section class="testimonials" id="testimonials">
    <div class="section-container">
      <div class="section-header">
        <div class="section-label">Testimonials</div>
        <h2 class="section-title">What our students say</h2>
      </div>
      <div class="testimonials-grid">
        <div class="testimonial-card">
          <div class="testimonial-stars">★★★★★</div>
          <p class="testimonial-text">"I've tried several apps, but StringMaster's interactive fretboard finally made chord transitions click for me. Went from zero to playing songs in 3 months!"</p>
          <div class="testimonial-author">
            <div class="testimonial-avatar">
              <img src="images/alex-student.jpg" alt="Alex Thompson">
            </div>
            <div>
              <div class="testimonial-name">Alex Thompson</div>
              <div class="testimonial-title">Beginner, 4 months</div>
            </div>
          </div>
        </div>
        <div class="testimonial-card">
          <div class="testimonial-stars">★★★★★</div>
          <p class="testimonial-text">"The AI feedback feature is incredible. It's like having a personal instructor available 24/7. My fingerpicking has improved dramatically."</p>
          <div class="testimonial-author">
            <div class="testimonial-avatar">
              <img src="images/maria-student.jpg" alt="Maria Garcia">
            </div>
            <div>
              <div class="testimonial-name">Maria Garcia</div>
              <div class="testimonial-title">Intermediate, 1 year</div>
            </div>
          </div>
        </div>
        <div class="testimonial-card">
          <div class="testimonial-stars">★★★★★</div>
          <p class="testimonial-text">"Worth every penny. The song library keeps me motivated, and the progress tracking shows exactly how far I've come. Highly recommend!"</p>
          <div class="testimonial-author">
            <div class="testimonial-avatar">
              <img src="images/david-student.jpg" alt="David Kim">
            </div>
            <div>
              <div class="testimonial-name">David Kim</div>
              <div class="testimonial-title">Pro subscriber, 8 months</div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

  <!-- CTA Section -->
  <section class="cta">
    <div class="section-container cta-content">
      <h2>Ready to start your guitar journey?</h2>
      <p>Join 50,000+ students learning guitar the modern way. Start your free trial today.</p>
      <a href="#pricing" class="btn-primary">Start Free Trial →</a>
    </div>
  </section>

  <!-- Footer -->
  <footer>
    <div class="footer-container">
      <div class="footer-grid">
        <div class="footer-brand">
          <a href="#" class="logo">
            <div class="logo-icon">♪</div>
            StringMaster
          </a>
          <p>The modern way to learn guitar. Interactive lessons, real-time feedback, and a supportive community.</p>
        </div>
        <div>
          <h4 class="footer-title">Product</h4>
          <ul class="footer-links">
            <li><a href="#">Features</a></li>
            <li><a href="#">Pricing</a></li>
            <li><a href="#">Song Library</a></li>
            <li><a href="#">Mobile App</a></li>
          </ul>
        </div>
        <div>
          <h4 class="footer-title">Company</h4>
          <ul class="footer-links">
            <li><a href="#">About Us</a></li>
            <li><a href="#">Careers</a></li>
            <li><a href="#">Blog</a></li>
            <li><a href="#">Contact</a></li>
          </ul>
        </div>
        <div>
          <h4 class="footer-title">Support</h4>
          <ul class="footer-links">
            <li><a href="#">Help Center</a></li>
            <li><a href="#">Community</a></li>
            <li><a href="#">Terms of Service</a></li>
            <li><a href="#">Privacy Policy</a></li>
          </ul>
        </div>
      </div>
      <div class="footer-bottom">
        <span>© 2026 StringMaster. All rights reserved.</span>
        <span>Developed by <a href="https://www.templatemo.com" target="_blank" rel="nofollow noopener">TemplateMo</a></span>
      </div>
    </div>
  </footer>

<script src="templatemo-606-string-scripts.js"></script>
</body>
</html>